##
# ODF Chart values
##
#

# ODF Version/Channel

odf:
# ODF Version/Channel
  channel: 'stable-4.9'
# Resource limits per service
  mon:
    requests:
       cpu: 1
       memory: 2Gi
  mds:
    requests:
      cpu: 3
      memory: 8Gi
  mgr:
    requests:
      cpu: 1
      memory: 3Gi
  noobaacore:
    requests:
      cpu: 1
      memory: 4Gi
  noobaadb:
    requests:
      cpu: 1
      memory: 4Gi
  osd:
    requests:
      cpu: 2
      memory: 5Gi
    limits:
      cpu: 3
      memory: 7Gi


# If RGW enabled, RGW object store will be deployed in AWS
rgw: 
  enabled: false
# Enable/Disable RGW SSL
  ssl: false

# If mcg enabled is set to False Nooba/Multicloud gateway will not be deployed.
mcg:
  enabled: false

# Deploy CephTools with ODF
cephtools:
  enabled: false

# If OCP Cluster is deployed in AWS and dedicated option enabled it will deploy 3 ODF workers(m5.4xlarge) using machinesets one per AZ, .
dedicated: 
  enabled: false
  aws:
    #you can use $ oc get machineset -n openshift-machine-api -o jsonpath='{.items[0].metadata.labels.machine\.openshift\.io/cluster-api-cluster}'
    clusterid: 'cluster-tlhvx-wmzb6'
    #youn can use $oc get machineset -n openshift-machine-api -o jsonpath='{.items[0].spec.template.spec.providerSpec.value.placement.region}' 
    region: 'us-east-2'
    #you can use $oc get machineset -n openshift-machine-api -o jsonpath='{.items[0].spec.template.spec.providerSpec.value.ami.id}'
    coreosami: 'ami-03d9208319c96db0c'

# Configure StorageCluster
osds:
# Number of OSDs that will be deployed deployed, this is the count inside the deviceset, so setting 1 equals to 3 OSDs, 2 = 6 OSDs, etc. 
  osdcount: 1
#Enable cluster OSD encription
  encryption:
    enabled: true
#Number of replicas for the default pools created for the ouf of the box ODF Storage Classes
  replicas: 3
#Storage Class that will be used to provision the ODF OSDs.
  scname: 'gp2'
#Size of Each PV that will be provisioned to be used by the OSDs.
  disksize: '512Gi'
  portable: true
