# Branch
gitBranchPro: main

# Namespaces config 
namespaceInfra: openshift-machine-api
namespaceODF: openshift-storage
namespaceLSO: openshift-local-storage
namespaceGitOps: openshift-gitops


# Global variables
global:

  # Public domain where apps will be published
  appsDomain: apps.acidonpe.sandbox1736.opentlc.com

  # Jump microservices settings
  apps:
    front-javascript:
      build: is
      imagestream: nodejs:latest
      imagestreamNamespace: openshift
      versions:
        - v1
      gitRepo: https://github.com/acidonper/jump-app-typescrypt-react.git
      type: nodejs
