---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-odf-deploy
spec:
  resources:
    - name: source-repo
      type: git
    - name: functional-test-repo
      type: git
  params:
    - name: git-branch  
      type: string
    - name: git-commit
      type: string
  tasks:
    - name: argocd-generate-cred-secret
      taskRef:
        name: argocd-generate-secret
    - name: machineset-deploy-by-argocd
      taskRef:
        name: argocd-task-sync-and-wait
      runAfter:
        - machineset-argocd-generate-cred-secret
      params:
        - name: argoapp
          value: "odf-machineset"
    - name: lso-deploy-by-argocd
      taskRef:
        name: argocd-task-sync-and-wait
      runAfter:
        - machineset-deploy-by-argocd
      params:
        - name: argoapp
          value: "deploy-lso"
    - name: operator-odf-deploy-by-argocd
      taskRef:
        name: argocd-task-sync-and-wait
      runAfter:
        - machineset-deploy-by-argocd
      params:
        - name: argoapp
          value: "deploy-odf-operator"
    - name: storagecluster-odf-deploy-by-argocd
      taskRef:
        name: argocd-task-sync-and-wait
      runAfter:
        - operator-odf-deploy-by-argocd
      params:
        - name: argoapp
          value: "deploy-odf-storagecluster"
