{{- range $key, $val := $.Values.global.apps }}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-{{ $key }}-build
spec:
  resources:
    - name: source-repo
      type: git
    - name: functional-test-repo
      type: git
  params:
    - name: git-branch  
      type: string
    - name: git-commit
      type: string
  tasks:
    - name: app-argocd-generate-cred-secret
      taskRef:
        name: argocd-generate-secret
    - name: app-image-deploy-by-argocd-dev
      taskRef:
        name: argocd-task-sync-and-wait
      runAfter:
        - app-argocd-generate-cred-secret
      params:
        - name: app
          value: '{{ $key }}'   
        - name: argoapp
          value: "{{ $.Values.namespaceDev }}"
        - name: commit
          value: "$(params.git-commit)"
    - name: app-image-deployment-test-dev
      taskRef:
        name: task-new-commit-image-deployment-test
      runAfter:
        - app-image-deploy-by-argocd-dev
      params:
        - name: namespace
          value: "{{ $.Values.namespaceDev }}"
        - name: deployment
          value: "{{ $key }}"
        - name: version
          value: "v1"
        - name: commit
          value: "$(params.git-commit)"
{{- end }}
