{{- range $key, $val := $.Values.global.apps }}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
  name: pipelinerun-pipeline-{{ $key }}-build-init-images
spec:
  serviceAccountName: {{ $.Values.sa }}
  pipelineRef:
    name: pipeline-{{ $key }}-build-init-images
{{- end }}
